from __future__ import annotations

from typing import Any, Dict, Iterable, Optional, Protocol


class HostAdapter(Protocol):
    """Runtime-neutral interface. Core Brain logic must not depend on one agent vendor."""

    def read_context(self, scope: str) -> Dict[str, Any]: ...
    def retrieve_history(self, query: str, scope: str) -> Iterable[Dict[str, Any]]: ...
    def list_capabilities(self, scope: str) -> Iterable[Dict[str, Any]]: ...
    def list_connections(self, scope: str) -> Iterable[Dict[str, Any]]: ...
    def authorize_action(self, request: Dict[str, Any]) -> Dict[str, Any]: ...
    def request_action(self, request: Dict[str, Any]) -> Dict[str, Any]: ...
    def request_evaluation(self, request: Dict[str, Any]) -> Dict[str, Any]: ...
    def schedule_trigger(self, trigger: Dict[str, Any]) -> Dict[str, Any]: ...
    def cancel_trigger(self, trigger_id: str) -> None: ...
    def notify_user(self, notification: Dict[str, Any]) -> None: ...
    def write_route(self, classification: str, payload: Dict[str, Any], scope: str) -> Optional[str]: ...
